spring:
main:
banner-mode: "off"
application:
name: it-ops-bot


server:
port: 8080


# Читаем из переменных окружения (в CI/VPS храните секреты там)
bot:
username: ${BOT_USERNAME:change_me}
token: ${BOT_TOKEN:change_me}
adminChatId: ${ADMIN_CHAT_ID:}


logging:
level:
root: INFO
com.example.itopsbot: INFO