version: "3.8"
services:
it-ops-bot:
build:
context: ../bot
container_name: it-ops-bot
environment:
BOT_USERNAME: ${BOT_USERNAME}
BOT_TOKEN: ${BOT_TOKEN}
TZ: Europe/Stockholm
volumes:
- /var/run/docker.sock:/var/run/docker.sock:ro
restart: unless-stopped