name: Build & Push Docker image (GHCR)

on:
  push:
    branches: [ "main" ]
    paths:
      - "bot/**"
      - ".github/workflows/build-and-push.yml"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/it-ops-bot:latest
            ghcr.io/${{ github.repository_owner }}/it-ops-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
