name: Build & Push Docker image (GHCR)

on:
  push:
    branches: ["main"]
    paths:
      - "bot/**"
      - ".github/workflows/build-and-push.yml"
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: bot

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21 with Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Build JAR (skip tests)
        run: ./gradlew --build-cache -Dorg.gradle.parallel=true -Dorg.gradle.configureondemand=true bootJar -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (single arch)
        uses: docker/build-push-action@v6
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: true
          platforms: linux/amd64        # << не собираем arm64 — в 2 раза быстрее
          tags: |
            ghcr.io/${{ github.repository_owner }}/it-ops-bot:latest
            ghcr.io/${{ github.repository_owner }}/it-ops-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
