name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build & Push Docker image (GHCR)"]
    types: [completed]
  workflow_dispatch: {}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT || 22 }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail

            APP_DIR="/opt/it-ops-bot/docker"
            cd "$APP_DIR"

            # тянем свежий образ и перезапускаем
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f

            # быстрый смоук-тест
            sleep 2
            docker compose -f docker-compose.prod.yml ps
